### ISSUE TITLE
isLegendary placeholder

### ISSUE THREAD

**Issue by joaoszaaa** [Neovitalism/PixelmonExtension#3]
Can you make a placeholder to verify if pokemon's party player is legendary?

like the shiny one

**Comment by Neovitalism** [comment]
Check the pokedex section on the wiki

**Comment by Neovitalism** [comment]
`%pixelmon_pokedex_[pokemonName/dexNumber]<:formName>_isLegend%`

**Comment by Neovitalism** [comment]
`%pixelmon_pokedex_[pokemonName/dexNumber]<:formName>_isLegend%`
