### ISSUE TITLE
Moves placeholder doesn't work with 3 or less moves

### ISSUE THREAD

**Issue by Steedr** [Neovitalism/PixelmonExtension#6]
Using `%pixelmon_party_[1-6]_moves%` on Pokemon with 3 or less moves doesn't work and throws this error:
https://pastebin.com/KyV4USu4
I didn't encounter this bug before updating to 9.0.8, so it could be something new

**Comment by Neovitalism** [comment]
Will fix tonight, out atm

**Comment by Neovitalism** [comment]
@Steedr can you replicate on 9.0.8a? I'm testing now and not getting the error.

**Comment by Steedr** [comment]
Still the same, but if it works for you, then there must be something wrong on my side

**Comment by Neovitalism** [comment]
Does moves_unlocalized break, too?

**Comment by Neovitalism** [comment]
Also, what version PlaceholderAPI?

**Comment by Steedr** [comment]
Oh, just noticed you released a new version, both localized and unlocalized works in 1.1.2

**Comment by Neovitalism** [comment]
Just noticed the last comment, that's super funny because I didn't actually touch moves in that update
